//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCUScanner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCUScanner.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to order.
        /// </summary>
        internal static string AddToOrderText {
            get {
                return ResourceManager.GetString("AddToOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm {0} hours.
        /// </summary>
        internal static string AlarmHoursText {
            get {
                return ResourceManager.GetString("AlarmHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm level {0}%.
        /// </summary>
        internal static string AlarmLevelText {
            get {
                return ResourceManager.GetString("AlarmLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Speed.
        /// </summary>
        internal static string AlarmSpeedText {
            get {
                return ResourceManager.GetString("AlarmSpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm at.
        /// </summary>
        internal static string AlarmText {
            get {
                return ResourceManager.GetString("AlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Columns.
        /// </summary>
        internal static string AllColumnsText {
            get {
                return ResourceManager.GetString("AllColumnsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is not enabled, enable Bluetooth?.
        /// </summary>
        internal static string AskBluetoothSetText {
            get {
                return ResourceManager.GetString("AskBluetoothSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth not available.
        ///Turn On Bluetooth and press .
        /// </summary>
        internal static string BlueToothTornOffText {
            get {
                return ResourceManager.GetString("BlueToothTornOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth unsupported.
        /// </summary>
        internal static string BluetoothUnsupportText {
            get {
                return ResourceManager.GetString("BluetoothUnsupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast identity.
        /// </summary>
        internal static string BroadcastIdentityText {
            get {
                return ResourceManager.GetString("BroadcastIdentityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast identity.
        /// </summary>
        internal static string BroadCastIdText {
            get {
                return ResourceManager.GetString("BroadCastIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ConnectButtonText {
            get {
                return ResourceManager.GetString("ConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string ConnectedDeviceCaptionText {
            get {
                return ResourceManager.GetString("ConnectedDeviceCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string ConnectingText {
            get {
                return ResourceManager.GetString("ConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ConnectStatusText {
            get {
                return ResourceManager.GetString("ConnectStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous scan.
        /// </summary>
        internal static string ContinuousScanText {
            get {
                return ResourceManager.GetString("ContinuousScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut off {0}%.
        /// </summary>
        internal static string CutOffText {
            get {
                return ResourceManager.GetString("CutOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DataText {
            get {
                return ResourceManager.GetString("DataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string DateWithTimeText {
            get {
                return ResourceManager.GetString("DateWithTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        internal static string DebugModeText {
            get {
                return ResourceManager.GetString("DebugModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        internal static string DeletingText {
            get {
                return ResourceManager.GetString("DeletingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string DeviceSettingsCaptionText {
            get {
                return ResourceManager.GetString("DeviceSettingsCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string DevicesText {
            get {
                return ResourceManager.GetString("DevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string DisConnectButtonText {
            get {
                return ResourceManager.GetString("DisConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string DisconnectedStatusText {
            get {
                return ResourceManager.GetString("DisconnectedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded .
        /// </summary>
        internal static string DownloadedText {
            get {
                return ResourceManager.GetString("DownloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New list.
        /// </summary>
        internal static string DownloadNewListText {
            get {
                return ResourceManager.GetString("DownloadNewListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download manual.
        /// </summary>
        internal static string DownloadText {
            get {
                return ResourceManager.GetString("DownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading, please wait ....
        /// </summary>
        internal static string DownloadWaitText {
            get {
                return ResourceManager.GetString("DownloadWaitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter serial number.
        /// </summary>
        internal static string EnterSerialNumberText {
            get {
                return ResourceManager.GetString("EnterSerialNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string EqualsText {
            get {
                return ResourceManager.GetString("EqualsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here to filter.
        /// </summary>
        internal static string FilterText {
            get {
                return ResourceManager.GetString("FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Elapsed.
        /// </summary>
        internal static string HoursElapsedText {
            get {
                return ResourceManager.GetString("HoursElapsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Run.
        /// </summary>
        internal static string HoursRunText {
            get {
                return ResourceManager.GetString("HoursRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access the hardware identifiers of nearby external devices via Bluetooth and Wi-Fi scans, your app must now have the ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permissions.
        /// </summary>
        internal static string InfoPermissionLocationText {
            get {
                return ResourceManager.GetString("InfoPermissionLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local image not found!!!.
        /// </summary>
        internal static string IsImageNotFoundText {
            get {
                return ResourceManager.GetString("IsImageNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length must be up to {0} characters.
        /// </summary>
        internal static string LengthMustBeText {
            get {
                return ResourceManager.GetString("LengthMustBeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of manuals.
        /// </summary>
        internal static string ListOfManualsText {
            get {
                return ResourceManager.GetString("ListOfManualsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        internal static string LocationNameText {
            get {
                return ResourceManager.GetString("LocationNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string MaintenanceText {
            get {
                return ResourceManager.GetString("MaintenanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainText {
            get {
                return ResourceManager.GetString("MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file not found.
        /// </summary>
        internal static string ManualNotFoundText {
            get {
                return ResourceManager.GetString("ManualNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual scan.
        /// </summary>
        internal static string ManualScanText {
            get {
                return ResourceManager.GetString("ManualScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Devices.
        /// </summary>
        internal static string NearbyDevicesCaptionText {
            get {
                return ResourceManager.GetString("NearbyDevicesCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet access or connection error. Open local copy of files.
        /// </summary>
        internal static string NoInternetConOrErrorText {
            get {
                return ResourceManager.GetString("NoInternetConOrErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEquals.
        /// </summary>
        internal static string NotEqualsText {
            get {
                return ResourceManager.GetString("NotEqualsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesText {
            get {
                return ResourceManager.GetString("NotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string OperatorNameText {
            get {
                return ResourceManager.GetString("OperatorNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string OperatorText {
            get {
                return ResourceManager.GetString("OperatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range will be between {0} and {1}.
        /// </summary>
        internal static string RangeWillBeValueText {
            get {
                return ResourceManager.GetString("RangeWillBeValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        internal static string RMPText {
            get {
                return ResourceManager.GetString("RMPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the units QR code.
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string ScanText {
            get {
                return ResourceManager.GetString("ScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        internal static string SelectAnOptionText {
            get {
                return ResourceManager.GetString("SelectAnOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SelectedLanguageCodeText {
            get {
                return ResourceManager.GetString("SelectedLanguageCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select part.
        /// </summary>
        internal static string SelectPartText {
            get {
                return ResourceManager.GetString("SelectPartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendButtonText {
            get {
                return ResourceManager.GetString("SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending value....
        /// </summary>
        internal static string SendingValueText {
            get {
                return ResourceManager.GetString("SendingValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.
        /// </summary>
        internal static string SerialNoText {
            get {
                return ResourceManager.GetString("SerialNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Android device select &quot;Settings&quot; &gt; &quot;Communication&quot; &gt; Bluetooth and make sure Bluetooth switch is in position &quot;On&quot;..
        /// </summary>
        internal static string SetHintBluetoothAndroidText {
            get {
                return ResourceManager.GetString("SetHintBluetoothAndroidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On your iOS device, tap Settings &gt; Bluetooth and make sure Bluetooth switch is in position &quot;On&quot;..
        /// </summary>
        internal static string SetHintBluetoothIOSText {
            get {
                return ResourceManager.GetString("SetHintBluetoothIOSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set serial number note this text
        ///box only visible on factory version.
        /// </summary>
        internal static string SetSerialNumberInfoText {
            get {
                return ResourceManager.GetString("SetSerialNumberInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set serial number.
        /// </summary>
        internal static string SetSerialNumberText {
            get {
                return ResourceManager.GetString("SetSerialNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show boundaries.
        /// </summary>
        internal static string SettingPartBorderText {
            get {
                return ResourceManager.GetString("SettingPartBorderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not edit this section.
        /// </summary>
        internal static string SharePartText2 {
            get {
                return ResourceManager.GetString("SharePartText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply your contact number below.
        /// </summary>
        internal static string SharePartText3 {
            get {
                return ResourceManager.GetString("SharePartText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare parts {0}.
        /// </summary>
        internal static string SharePartTitle {
            get {
                return ResourceManager.GetString("SharePartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show part number.
        /// </summary>
        internal static string ShowPartNumText {
            get {
                return ResourceManager.GetString("ShowPartNumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show serial number.
        /// </summary>
        internal static string ShowSerialNumberText {
            get {
                return ResourceManager.GetString("ShowSerialNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spares.
        /// </summary>
        internal static string SparesText {
            get {
                return ResourceManager.GetString("SparesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string SpeedText {
            get {
                return ResourceManager.GetString("SpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Scan.
        /// </summary>
        internal static string StopScanText {
            get {
                return ResourceManager.GetString("StopScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string UnitNameText {
            get {
                return ResourceManager.GetString("UnitNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use existing list.
        /// </summary>
        internal static string UseExistingListText {
            get {
                return ResourceManager.GetString("UseExistingListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait {0} seconds for its internal reboot  and then re-connect .
        /// </summary>
        internal static string WaitForChangeIDText {
            get {
                return ResourceManager.GetString("WaitForChangeIDText", resourceCulture);
            }
        }
    }
}
