//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCUScanner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCUScanner.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is not enabled, enable Bluetooth?.
        /// </summary>
        internal static string AskBluetoothSetText {
            get {
                return ResourceManager.GetString("AskBluetoothSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth not available.
        ///Turn On Bluetooth and press .
        /// </summary>
        internal static string BlueToothTornOffText {
            get {
                return ResourceManager.GetString("BlueToothTornOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth unsupported.
        /// </summary>
        internal static string BluetoothUnsupportText {
            get {
                return ResourceManager.GetString("BluetoothUnsupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ConnectButtonText {
            get {
                return ResourceManager.GetString("ConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Device.
        /// </summary>
        internal static string ConnectedDeviceCaptionText {
            get {
                return ResourceManager.GetString("ConnectedDeviceCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string ConnectingText {
            get {
                return ResourceManager.GetString("ConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ConnectStatusText {
            get {
                return ResourceManager.GetString("ConnectStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous scan.
        /// </summary>
        internal static string ContinuousScanText {
            get {
                return ResourceManager.GetString("ContinuousScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DataText {
            get {
                return ResourceManager.GetString("DataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Settings.
        /// </summary>
        internal static string DeviceSettingsCaptionText {
            get {
                return ResourceManager.GetString("DeviceSettingsCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string DevicesText {
            get {
                return ResourceManager.GetString("DevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string DisConnectButtonText {
            get {
                return ResourceManager.GetString("DisConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string DisconnectedStatusText {
            get {
                return ResourceManager.GetString("DisconnectedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Manual.
        /// </summary>
        internal static string DownloadText {
            get {
                return ResourceManager.GetString("DownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access the hardware identifiers of nearby external devices via Bluetooth and Wi-Fi scans, your app must now have the ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permissions.
        /// </summary>
        internal static string InfoPermissionLocationText {
            get {
                return ResourceManager.GetString("InfoPermissionLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        internal static string LocationNameText {
            get {
                return ResourceManager.GetString("LocationNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string MaintenanceText {
            get {
                return ResourceManager.GetString("MaintenanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Devices.
        /// </summary>
        internal static string MainText {
            get {
                return ResourceManager.GetString("MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual scan.
        /// </summary>
        internal static string ManualScanText {
            get {
                return ResourceManager.GetString("ManualScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Devices.
        /// </summary>
        internal static string NearbyDevicesCaptionText {
            get {
                return ResourceManager.GetString("NearbyDevicesCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string OperatorNameText {
            get {
                return ResourceManager.GetString("OperatorNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string ScanText {
            get {
                return ResourceManager.GetString("ScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SelectedLanguageCodeText {
            get {
                return ResourceManager.GetString("SelectedLanguageCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Android device select &quot;Settings&quot; &gt; &quot;Communication&quot; &gt; Bluetooth and make sure Bluetooth switch is in position &quot;On&quot;..
        /// </summary>
        internal static string SetHintBluetoothAndroidText {
            get {
                return ResourceManager.GetString("SetHintBluetoothAndroidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On your iOS device, tap Settings &gt; Bluetooth and make sure Bluetooth switch is in position &quot;On&quot;..
        /// </summary>
        internal static string SetHintBluetoothIOSText {
            get {
                return ResourceManager.GetString("SetHintBluetoothIOSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spares.
        /// </summary>
        internal static string SparesText {
            get {
                return ResourceManager.GetString("SparesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Scan.
        /// </summary>
        internal static string StopScanText {
            get {
                return ResourceManager.GetString("StopScanText", resourceCulture);
            }
        }
    }
}
